
# CONFIGURATION D'URGENCE POST-BLOCAGE
EMERGENCY_MODE = True
BATCH_SIZE = 2
MESSAGE_DELAY_MIN = 20
MESSAGE_DELAY_MAX = 45
BATCH_DELAY_MIN = 900  # 15 minutes
BATCH_DELAY_MAX = 1500  # 25 minutes
MAX_DAILY_MESSAGES = 50
MAX_WORKERS = 1
